version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}"
          repo: "cicd"
          region: $AWS_REGION_ENV_VAR_NAME
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          context: my_aws
          aws-region: $AWS_REGION_ENV_VAR_NAME
          family: "cicd-service"
          cluster-name: "cicd-cluster"
          container-image-name-updates: "container=cicd-service,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_REGION_ENV_VAR_NAME.amazonaws.com/cicd:${CIRCLE_SHA1}"
          verify-revision-is-deployed: true
